spring:
  profiles:
    active:
    - dev
---
server:
  prot: 7001 #注册中心占用7001端口

spring:
  profiles: dev
  application: 
    name: microservicecloud-config-eureka-client
    
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    server-url:
      defaultZone: http://eureka7001.com:7001/eureka/
---
server:
  prot: 7001 #注册中心占用7001端口

spring:
  profiles: test
  application: 
    name: microservicecloud-config-eureka-client

eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    server-url:
      defaultZone: http://eureka7001.com:7001/eureka/